
#DB Configuration - (dev-prod)
#spring.datasource.url=jdbc:mysql://localhost:3306/blog_app_apis
#spring.datasource.username=root
#spring.datasource.password=1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#Hibernate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

#Hibernet auto DDL create, update, create-drop, validate
spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true

# File related all configuration - upload File and serve
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

#Path - for file/image
project.image=images/

#Security
logging.level.org.springframework.security=DEBUG
#No need comes from Database:
#spring.security.user.name=akshay
#spring.security.user.password=12345
#spring.security.user.roles=ADMIN

#API Documentation - Swagger
springdoc.packagesToScan=com.blog.controller
springdoc.pathsToMatch=/api/**, /auth/**, /v1, /v2, /v3, /categories/**, /comments/**, /posts/**, /users/**

spring.profiles.active=dev

